$(error do not use this plugin - it is sorely broken. Use ../ncurses-oo instead!)
PLUGIN_NAME := ncurses
PLUGIN_OBJECTS := nccolors.o ncmode.o ncstream.o v8-ncurses.o
PLUGIN_LDADD := -lpanel -lncurses
include ../plugin_template.make
