PLUGIN_NAME := readline
PLUGIN_OBJECTS := Readline.o v8-dll.o
# To use libedit, change:
#  PLUGIN_LDADD := -ledit
# edit Readline_config.hpp, and recompile
PLUGIN_LDADD := -lreadline
include ../plugin_template.make
